/******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Port Driver
 *
 * Author: Shehab Kishta
 ******************************************************************************/

#include "Port.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between PORT_PBcfg.c and PORT.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between PORT_PBcfg.c and PORT.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif

const Port_ConfigType Port_Configuration = {
    PORTA_NUM, PIN0_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PA0 */
    PORTA_NUM, PIN1_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PA1 */
    PORTA_NUM, PIN2_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PA2 */
    PORTA_NUM, PIN3_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PA3 */
    PORTA_NUM, PIN4_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PA4 */
    PORTA_NUM, PIN5_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PA5 */
    PORTA_NUM, PIN6_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PA6 */
    PORTA_NUM, PIN7_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PA7 */
    PORTB_NUM, PIN0_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PB0 */
    PORTB_NUM, PIN1_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PB1 */
    PORTB_NUM, PIN2_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PB2 */
    PORTB_NUM, PIN3_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PB3 */
    PORTB_NUM, PIN4_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PB4 */
    PORTB_NUM, PIN5_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PB5 */
    PORTB_NUM, PIN6_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PB6 */
    PORTB_NUM, PIN7_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PB7 */
    PORTC_NUM, PIN0_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PC0 */
    PORTC_NUM, PIN1_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PC1 */
    PORTC_NUM, PIN2_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PC2 */
    PORTC_NUM, PIN3_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PC3 */
    PORTC_NUM, PIN4_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PC4 */
    PORTC_NUM, PIN5_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PC5 */
    PORTC_NUM, PIN6_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PC6 */
    PORTC_NUM, PIN7_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PC7 */
    PORTD_NUM, PIN0_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PD0 */
    PORTD_NUM, PIN1_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PD1 */
    PORTD_NUM, PIN2_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PD2 */
    PORTD_NUM, PIN3_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PD3 */
    PORTD_NUM, PIN4_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PD4 */
    PORTD_NUM, PIN5_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PD5 */
    PORTD_NUM, PIN6_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PD6 */
    PORTD_NUM, PIN7_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PD7 */
    PORTE_NUM, PIN0_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PE0 */
    PORTE_NUM, PIN1_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PE1 */
    PORTE_NUM, PIN2_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PE2 */
    PORTE_NUM, PIN3_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PE3 */
    PORTE_NUM, PIN4_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PE4 */
    PORTE_NUM, PIN5_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PE5 */
    PORTF_NUM, PIN0_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,         /* PF0 */
    PORTF_NUM, PIN1_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION_LED, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,    /* PF1 */
    PORTF_NUM, PIN2_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,         /* PF2 */
    PORTF_NUM, PIN3_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, DEFAULT_PORT_PULL_UP_ENABLE, DEFAULT_PORT_PULL_DOWN_ENABLE,         /* PF3 */
    PORTF_NUM, PIN4_NUM, PORT_PIN_INITIAL_MODE, PORT_PIN_DIRECTION, PORT_PIN_INIT_VALUE, PORT_PIN_DIRECTION_CHANGEABLE_DEFAULT, PORT_PIN_MODE_CHANGEABLE_DEFAULT, DEFAULT_PORT_ANALOG_ENABLE, DEFAULT_PORT_DIGITAL_ENABLE, STD_ON, DEFAULT_PORT_PULL_DOWN_ENABLE                               /* PF4 */
};